### PR TITLE
Bounding Box checking fix

### PR DESCRIPTION
**Pull request by MadsLudvig**

### CODE REVIEW

**Comment by MadsLudvig** [comment]
This branch needs to be tested with move-fix branch on Magicboard-server

**Review by krestenlaust — CHANGES_REQUESTED** [review]
Deployede den til Marcs server, den crashede:
```
$ docker logs magic_board
Listening on 0.0.0.0:3000
node:internal/deps/undici/undici:12618
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at async validateBoardId (file:///app/build/server/chunks/http-97ONXHi3.js:11:20) {
  cause: SocketError: other side closed
      at Socket.onSocketEnd (node:internal/deps/undici/undici:9169:26)
      at Socket.emit (node:events:529:35)
      at endReadableNT (node:internal/streams/readable:1400:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '172.17.0.3',
      localPort: 36196,
      remoteAddress: undefined,
      remotePort: undefined,
      remoteFamily: undefined,
      timeout: undefined,
      bytesWritten: 265,
      bytesRead: 0
    }
  }
}

Node.js v18.20.2
```

**Comment by MadsLudvig** [comment]
> Deployede den til Marcs server, den crashede:
> 
> ```
> $ docker logs magic_board
> Listening on 0.0.0.0:3000
> node:internal/deps/undici/undici:12618
>     Error.captureStackTrace(err, this);
>           ^
> 
> TypeError: fetch failed
>     at node:internal/deps/undici/undici:12618:11
>     at async validateBoardId (file:///app/build/server/chunks/http-97ONXHi3.js:11:20) {
>   cause: SocketError: other side closed
>       at Socket.onSocketEnd (node:internal/deps/undici/undici:9169:26)
>       at Socket.emit (node:events:529:35)
>       at endReadableNT (node:internal/streams/readable:1400:12)
>       at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>     code: 'UND_ERR_SOCKET',
>     socket: {
>       localAddress: '172.17.0.3',
>       localPort: 36196,
>       remoteAddress: undefined,
>       remotePort: undefined,
>       remoteFamily: undefined,
>       timeout: undefined,
>       bytesWritten: 265,
>       bytesRead: 0
>     }
>   }
> }
> 
> Node.js v18.20.2
> ```

Tror at det har været requests i http.ts filen der ikke havde ordentlig error handling. Har tilføjet try-catch rundt om requests

**Review by krestenlaust — APPROVED** [review]
Ser godt ud

**Pull request merged**
